name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      - name: Docker Build
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Docker Tag
        run: docker tag ${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/${{ github.sha }}
      - name: Docker Push
        run: docker push v1sion0106/v1flix:${{ github.sha }}
